### ISSUE TITLE
idena-node docker image

### ISSUE THREAD

**Issue by Rinzler78** [bingbinglee/idena-apps#10]
Hi, 

I've made a ready to run idena-node public docker image 
=> https://hub.docker.com/r/rinzlerfr/idena-node

Source are public too 
=> https://github.com/Rinzler78/docker.idena-node

Let me know If you have questions or want details.

have a nice day

**Comment by bingbinglee** [comment]
Added via https://github.com/bingbinglee/idena-apps/commit/c528d4c52807d8bcc157e1f8e494d5b13a20fe2f
