### ISSUE TITLE
add playidena.com - gambling site for idena

### ISSUE THREAD

**Issue by codev911** [bingbinglee/idena-apps#11]
- apps / gambling
- Playidena / Play games and earn Idena up to 500%
- @codev911 & @alice-node
- https://playidena.com/
- https://imgur.com/a/6iIYF2f
- https://t.me/gcyber & https://t.me/ubaygates

**Comment by bingbinglee** [comment]
Added via https://github.com/bingbinglee/idena-apps/commit/c3c32ff147c1322633652a7e4247c58dd693ddf7
