### ISSUE TITLE
Community - Philippines Community

### ISSUE THREAD

**Issue by Syd-ai** [bingbinglee/idena-apps#17]
- Community
- Idena Philippines 
- http://t.me/idena_PH
- thumbnail URL 
![photo_2020-08-27_16-31-19](https://user-images.githubusercontent.com/58671114/110726341-83aedb00-8219-11eb-8053-21aee780d534.jpg)

**Comment by bingbinglee** [comment]
Added via https://github.com/bingbinglee/idena-apps/commit/22b7f85c2ab0bc8032af2f60c60aeaa4cebd4676
