### ISSUE TITLE
Icon broken

### ISSUE THREAD

**Issue by Endogen** [bingbinglee/idena-apps#8]
The icon on the left under "Communities" is broken
![image](https://user-images.githubusercontent.com/226475/80569733-d284c500-89f9-11ea-8a22-861437990b1f.png)

**Comment by bingbinglee** [comment]
This is fixed. thanks for pointing out - https://github.com/bingbinglee/idena-apps/commit/80c8ac3abca6de6ff146f59d6ae86547e29a440e
